// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryContacts = `-- name: ClearPrimaryContacts :exec
UPDATE user_contact_points
SET is_primary = FALSE
WHERE user_id = $1
  AND contact_type = $2
  AND deleted_at IS NULL
  AND is_primary = TRUE
  AND id <> $3
`

type ClearPrimaryContactsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ContactType string    `json:"contact_type"`
	ExcludeID   uuid.UUID `json:"exclude_id"`
}

func (q *Queries) ClearPrimaryContacts(ctx context.Context, arg ClearPrimaryContactsParams) error {
	_, err := q.db.Exec(ctx, clearPrimaryContacts, arg.UserID, arg.ContactType, arg.ExcludeID)
	return err
}

const createContact = `-- name: CreateContact :one
INSERT INTO user_contact_points (
  user_id, contact_type, label, value, is_primary, is_preferred,
  allow_contact, preferred_time_window, note, created_by, updated_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, $10
)
RETURNING id, user_id, contact_type, label, value, is_primary, is_preferred,
          allow_contact, preferred_time_window, verified_at, note, created_at, updated_at
`

type CreateContactParams struct {
	UserID              uuid.UUID     `json:"user_id"`
	ContactType         string        `json:"contact_type"`
	Label               pgtype.Text   `json:"label"`
	Value               string        `json:"value"`
	IsPrimary           bool          `json:"is_primary"`
	IsPreferred         bool          `json:"is_preferred"`
	AllowContact        bool          `json:"allow_contact"`
	PreferredTimeWindow pgtype.Text   `json:"preferred_time_window"`
	Note                pgtype.Text   `json:"note"`
	Actor               uuid.NullUUID `json:"actor"`
}

type CreateContactRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	ContactType         string             `json:"contact_type"`
	Label               pgtype.Text        `json:"label"`
	Value               string             `json:"value"`
	IsPrimary           bool               `json:"is_primary"`
	IsPreferred         bool               `json:"is_preferred"`
	AllowContact        bool               `json:"allow_contact"`
	PreferredTimeWindow pgtype.Text        `json:"preferred_time_window"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (CreateContactRow, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.UserID,
		arg.ContactType,
		arg.Label,
		arg.Value,
		arg.IsPrimary,
		arg.IsPreferred,
		arg.AllowContact,
		arg.PreferredTimeWindow,
		arg.Note,
		arg.Actor,
	)
	var i CreateContactRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactType,
		&i.Label,
		&i.Value,
		&i.IsPrimary,
		&i.IsPreferred,
		&i.AllowContact,
		&i.PreferredTimeWindow,
		&i.VerifiedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, user_id, contact_type, label, value, is_primary, is_preferred,
       allow_contact, preferred_time_window, verified_at, note, created_at, updated_at
FROM user_contact_points
WHERE id = $1 AND deleted_at IS NULL
`

type GetContactRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	ContactType         string             `json:"contact_type"`
	Label               pgtype.Text        `json:"label"`
	Value               string             `json:"value"`
	IsPrimary           bool               `json:"is_primary"`
	IsPreferred         bool               `json:"is_preferred"`
	AllowContact        bool               `json:"allow_contact"`
	PreferredTimeWindow pgtype.Text        `json:"preferred_time_window"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (GetContactRow, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i GetContactRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactType,
		&i.Label,
		&i.Value,
		&i.IsPrimary,
		&i.IsPreferred,
		&i.AllowContact,
		&i.PreferredTimeWindow,
		&i.VerifiedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, user_id, contact_type, label, value, is_primary, is_preferred,
       allow_contact, preferred_time_window, verified_at, note, created_at, updated_at
FROM user_contact_points
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY contact_type, created_at, id
`

type ListContactsRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	ContactType         string             `json:"contact_type"`
	Label               pgtype.Text        `json:"label"`
	Value               string             `json:"value"`
	IsPrimary           bool               `json:"is_primary"`
	IsPreferred         bool               `json:"is_preferred"`
	AllowContact        bool               `json:"allow_contact"`
	PreferredTimeWindow pgtype.Text        `json:"preferred_time_window"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListContacts(ctx context.Context, userID uuid.UUID) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsRow{}
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContactType,
			&i.Label,
			&i.Value,
			&i.IsPrimary,
			&i.IsPreferred,
			&i.AllowContact,
			&i.PreferredTimeWindow,
			&i.VerifiedAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteContact = `-- name: SoftDeleteContact :exec
UPDATE user_contact_points
SET deleted_at = NOW(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteContactParams struct {
	UpdatedBy uuid.NullUUID `json:"updated_by"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error {
	_, err := q.db.Exec(ctx, softDeleteContact, arg.UpdatedBy, arg.ID)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE user_contact_points
SET label = $1,
    value = $2,
    is_primary = $3,
    is_preferred = $4,
    allow_contact = $5,
    preferred_time_window = $6,
    note = $7,
    updated_by = $8
WHERE id = $9 AND deleted_at IS NULL
RETURNING id, user_id, contact_type, label, value, is_primary, is_preferred,
          allow_contact, preferred_time_window, verified_at, note, created_at, updated_at
`

type UpdateContactParams struct {
	Label               pgtype.Text   `json:"label"`
	Value               string        `json:"value"`
	IsPrimary           bool          `json:"is_primary"`
	IsPreferred         bool          `json:"is_preferred"`
	AllowContact        bool          `json:"allow_contact"`
	PreferredTimeWindow pgtype.Text   `json:"preferred_time_window"`
	Note                pgtype.Text   `json:"note"`
	UpdatedBy           uuid.NullUUID `json:"updated_by"`
	ID                  uuid.UUID     `json:"id"`
}

type UpdateContactRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	ContactType         string             `json:"contact_type"`
	Label               pgtype.Text        `json:"label"`
	Value               string             `json:"value"`
	IsPrimary           bool               `json:"is_primary"`
	IsPreferred         bool               `json:"is_preferred"`
	AllowContact        bool               `json:"allow_contact"`
	PreferredTimeWindow pgtype.Text        `json:"preferred_time_window"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (UpdateContactRow, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Label,
		arg.Value,
		arg.IsPrimary,
		arg.IsPreferred,
		arg.AllowContact,
		arg.PreferredTimeWindow,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
	)
	var i UpdateContactRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContactType,
		&i.Label,
		&i.Value,
		&i.IsPrimary,
		&i.IsPreferred,
		&i.AllowContact,
		&i.PreferredTimeWindow,
		&i.VerifiedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
