// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crm.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAddress = `-- name: GetUserAddress :one
SELECT user_id, company, care_of, street1, street2, postal_code, city, state, country_code, note, created_at, updated_at
FROM user_address
WHERE user_id = $1
`

type GetUserAddressRow struct {
	UserID      uuid.UUID          `json:"user_id"`
	Company     pgtype.Text        `json:"company"`
	CareOf      pgtype.Text        `json:"care_of"`
	Street1     string             `json:"street1"`
	Street2     pgtype.Text        `json:"street2"`
	PostalCode  string             `json:"postal_code"`
	City        string             `json:"city"`
	State       pgtype.Text        `json:"state"`
	CountryCode string             `json:"country_code"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserAddress(ctx context.Context, userID uuid.UUID) (GetUserAddressRow, error) {
	row := q.db.QueryRow(ctx, getUserAddress, userID)
	var i GetUserAddressRow
	err := row.Scan(
		&i.UserID,
		&i.Company,
		&i.CareOf,
		&i.Street1,
		&i.Street2,
		&i.PostalCode,
		&i.City,
		&i.State,
		&i.CountryCode,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, preferred_contact_type, note, updated_at
FROM user_preferences
WHERE user_id = $1
`

type GetUserPreferencesRow struct {
	UserID               uuid.UUID          `json:"user_id"`
	PreferredContactType pgtype.Text        `json:"preferred_contact_type"`
	Note                 pgtype.Text        `json:"note"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (GetUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i GetUserPreferencesRow
	err := row.Scan(
		&i.UserID,
		&i.PreferredContactType,
		&i.Note,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserAddress = `-- name: UpsertUserAddress :one
INSERT INTO user_address (
  user_id, company, care_of, street1, street2, postal_code, city, state, country_code, note, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10,
  $11, $11
)
ON CONFLICT (user_id) DO UPDATE SET
  company = EXCLUDED.company,
  care_of = EXCLUDED.care_of,
  street1 = EXCLUDED.street1,
  street2 = EXCLUDED.street2,
  postal_code = EXCLUDED.postal_code,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  country_code = EXCLUDED.country_code,
  note = EXCLUDED.note,
  updated_by = EXCLUDED.updated_by
RETURNING user_id, company, care_of, street1, street2, postal_code, city, state, country_code, note, created_at, updated_at
`

type UpsertUserAddressParams struct {
	UserID      uuid.UUID     `json:"user_id"`
	Company     pgtype.Text   `json:"company"`
	CareOf      pgtype.Text   `json:"care_of"`
	Street1     string        `json:"street1"`
	Street2     pgtype.Text   `json:"street2"`
	PostalCode  string        `json:"postal_code"`
	City        string        `json:"city"`
	State       pgtype.Text   `json:"state"`
	CountryCode string        `json:"country_code"`
	Note        pgtype.Text   `json:"note"`
	Actor       uuid.NullUUID `json:"actor"`
}

type UpsertUserAddressRow struct {
	UserID      uuid.UUID          `json:"user_id"`
	Company     pgtype.Text        `json:"company"`
	CareOf      pgtype.Text        `json:"care_of"`
	Street1     string             `json:"street1"`
	Street2     pgtype.Text        `json:"street2"`
	PostalCode  string             `json:"postal_code"`
	City        string             `json:"city"`
	State       pgtype.Text        `json:"state"`
	CountryCode string             `json:"country_code"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserAddress(ctx context.Context, arg UpsertUserAddressParams) (UpsertUserAddressRow, error) {
	row := q.db.QueryRow(ctx, upsertUserAddress,
		arg.UserID,
		arg.Company,
		arg.CareOf,
		arg.Street1,
		arg.Street2,
		arg.PostalCode,
		arg.City,
		arg.State,
		arg.CountryCode,
		arg.Note,
		arg.Actor,
	)
	var i UpsertUserAddressRow
	err := row.Scan(
		&i.UserID,
		&i.Company,
		&i.CareOf,
		&i.Street1,
		&i.Street2,
		&i.PostalCode,
		&i.City,
		&i.State,
		&i.CountryCode,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (user_id, preferred_contact_type, note, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
  preferred_contact_type = EXCLUDED.preferred_contact_type,
  note = EXCLUDED.note,
  updated_by = EXCLUDED.updated_by
RETURNING user_id, preferred_contact_type, note, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID               uuid.UUID     `json:"user_id"`
	PreferredContactType pgtype.Text   `json:"preferred_contact_type"`
	Note                 pgtype.Text   `json:"note"`
	Actor                uuid.NullUUID `json:"actor"`
}

type UpsertUserPreferencesRow struct {
	UserID               uuid.UUID          `json:"user_id"`
	PreferredContactType pgtype.Text        `json:"preferred_contact_type"`
	Note                 pgtype.Text        `json:"note"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UpsertUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences,
		arg.UserID,
		arg.PreferredContactType,
		arg.Note,
		arg.Actor,
	)
	var i UpsertUserPreferencesRow
	err := row.Scan(
		&i.UserID,
		&i.PreferredContactType,
		&i.Note,
		&i.UpdatedAt,
	)
	return i, err
}
