// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :exec
INSERT INTO group_members (group_id, user_id, role_in_group, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (group_id, user_id) DO UPDATE SET role_in_group = EXCLUDED.role_in_group
`

type AddMemberParams struct {
	GroupID     uuid.UUID     `json:"group_id"`
	UserID      uuid.UUID     `json:"user_id"`
	RoleInGroup string        `json:"role_in_group"`
	CreatedBy   uuid.NullUUID `json:"created_by"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember,
		arg.GroupID,
		arg.UserID,
		arg.RoleInGroup,
		arg.CreatedBy,
	)
	return err
}

const listMembers = `-- name: ListMembers :many
SELECT gm.user_id, u.first_name, u.last_name, u.email, gm.role_in_group, gm.joined_at
FROM group_members gm
JOIN users u ON u.id = gm.user_id AND u.deleted_at IS NULL
WHERE gm.group_id = $1
ORDER BY u.last_name, u.first_name, gm.user_id
`

type ListMembersRow struct {
	UserID      uuid.UUID          `json:"user_id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       string             `json:"email"`
	RoleInGroup string             `json:"role_in_group"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListMembers(ctx context.Context, groupID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.RoleInGroup,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.group_type, gm.role_in_group, gm.joined_at
FROM group_members gm
JOIN groups g ON g.id = gm.group_id AND g.deleted_at IS NULL
WHERE gm.user_id = $1
ORDER BY g.name, g.id
`

type ListUserGroupsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	GroupType   string             `json:"group_type"`
	RoleInGroup string             `json:"role_in_group"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserGroupsRow{}
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupType,
			&i.RoleInGroup,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.GroupID, arg.UserID)
	return err
}
