// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, group_type, created_by, updated_by)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, name, description, group_type, is_active, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string        `json:"name"`
	Description pgtype.Text   `json:"description"`
	GroupType   string        `json:"group_type"`
	Actor       uuid.NullUUID `json:"actor"`
}

type CreateGroupRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	GroupType   string             `json:"group_type"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.GroupType,
		arg.Actor,
	)
	var i CreateGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GroupType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, group_type, is_active, created_at, updated_at
FROM groups
WHERE id = $1 AND deleted_at IS NULL
`

type GetGroupByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	GroupType   string             `json:"group_type"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (GetGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i GetGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GroupType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, group_type, is_active, created_at, updated_at
FROM groups
WHERE deleted_at IS NULL
ORDER BY name, id
LIMIT $1 OFFSET $2
`

type ListGroupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListGroupsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	GroupType   string             `json:"group_type"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GroupType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByType = `-- name: ListGroupsByType :many
SELECT id, name, description, group_type, is_active, created_at, updated_at
FROM groups
WHERE deleted_at IS NULL AND group_type = $1
ORDER BY name, id
LIMIT $2 OFFSET $3
`

type ListGroupsByTypeParams struct {
	GroupType string `json:"group_type"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListGroupsByTypeRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	GroupType   string             `json:"group_type"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListGroupsByType(ctx context.Context, arg ListGroupsByTypeParams) ([]ListGroupsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listGroupsByType, arg.GroupType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsByTypeRow{}
	for rows.Next() {
		var i ListGroupsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GroupType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE groups
SET deleted_at = NOW(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteGroupParams struct {
	UpdatedBy uuid.NullUUID `json:"updated_by"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) SoftDeleteGroup(ctx context.Context, arg SoftDeleteGroupParams) error {
	_, err := q.db.Exec(ctx, softDeleteGroup, arg.UpdatedBy, arg.ID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $1,
    description = $2,
    group_type = $3,
    is_active = $4,
    updated_by = $5
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, name, description, group_type, is_active, created_at, updated_at
`

type UpdateGroupParams struct {
	Name        string        `json:"name"`
	Description pgtype.Text   `json:"description"`
	GroupType   string        `json:"group_type"`
	IsActive    bool          `json:"is_active"`
	UpdatedBy   uuid.NullUUID `json:"updated_by"`
	ID          uuid.UUID     `json:"id"`
}

type UpdateGroupRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	GroupType   string             `json:"group_type"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UpdateGroupRow, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.Description,
		arg.GroupType,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
	)
	var i UpdateGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GroupType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
