// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountingAccount struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	AccountType string `json:"account_type"`
}

type AccountingEntry struct {
	ID          uuid.UUID          `json:"id"`
	JournalID   uuid.UUID          `json:"journal_id"`
	AccountCode string             `json:"account_code"`
	Debit       pgtype.Numeric     `json:"debit"`
	Credit      pgtype.Numeric     `json:"credit"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

type AccountingJournal struct {
	ID              uuid.UUID          `json:"id"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	Description     string             `json:"description"`
	ReferenceType   pgtype.Text        `json:"reference_type"`
	ReferencePk     pgtype.Text        `json:"reference_pk"`
	IsLocked        bool               `json:"is_locked"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Applicant struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	AppliedAt         pgtype.Date        `json:"applied_at"`
	PreferredUnitType pgtype.Text        `json:"preferred_unit_type"`
	PreferredAreaMin  pgtype.Numeric     `json:"preferred_area_min"`
	Status            string             `json:"status"`
	WaitlistPosition  pgtype.Int4        `json:"waitlist_position"`
	AssignedUnitID    uuid.NullUUID      `json:"assigned_unit_id"`
	Note              pgtype.Text        `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy         uuid.NullUUID      `json:"created_by"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
}

type AuditLog struct {
	ID          uuid.UUID          `json:"id"`
	TableName   string             `json:"table_name"`
	RecordPk    string             `json:"record_pk"`
	Action      string             `json:"action"`
	OldData     []byte             `json:"old_data"`
	NewData     []byte             `json:"new_data"`
	ActorUserID uuid.NullUUID      `json:"actor_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BankAccount struct {
	ID         uuid.UUID          `json:"id"`
	IbanMasked string             `json:"iban_masked"`
	Name       pgtype.Text        `json:"name"`
	Note       pgtype.Text        `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy  uuid.NullUUID      `json:"created_by"`
}

type BankCategorizationRule struct {
	ID                  uuid.UUID          `json:"id"`
	Pattern             string             `json:"pattern"`
	Field               string             `json:"field"`
	CategoryAccountCode string             `json:"category_account_code"`
	Priority            int32              `json:"priority"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy           uuid.NullUUID      `json:"created_by"`
}

type BankImportLog struct {
	ID                uuid.UUID          `json:"id"`
	Filename          string             `json:"filename"`
	Format            string             `json:"format"`
	DetectedIban      pgtype.Text        `json:"detected_iban"`
	TotalRows         int32              `json:"total_rows"`
	ImportedRows      int32              `json:"imported_rows"`
	SkippedDuplicates int32              `json:"skipped_duplicates"`
	BankAccountID     uuid.NullUUID      `json:"bank_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         uuid.NullUUID      `json:"created_by"`
}

type BankTransaction struct {
	ID                  uuid.UUID          `json:"id"`
	BankAccountID       uuid.UUID          `json:"bank_account_id"`
	TransactionDate     pgtype.Date        `json:"transaction_date"`
	Amount              pgtype.Numeric     `json:"amount"`
	Payee               pgtype.Text        `json:"payee"`
	Description         pgtype.Text        `json:"description"`
	Source              string             `json:"source"`
	ChecksumSha256      pgtype.Text        `json:"checksum_sha256"`
	CategoryAccountCode pgtype.Text        `json:"category_account_code"`
	JournalID           uuid.NullUUID      `json:"journal_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy           uuid.NullUUID      `json:"created_by"`
	SearchVector        interface{}        `json:"search_vector"`
}

type BillingItem struct {
	ID              uuid.UUID          `json:"id"`
	BillingPeriodID uuid.UUID          `json:"billing_period_id"`
	LeaseID         uuid.UUID          `json:"lease_id"`
	UnitID          uuid.UUID          `json:"unit_id"`
	TenantUserID    uuid.UUID          `json:"tenant_user_id"`
	ItemType        string             `json:"item_type"`
	Description     pgtype.Text        `json:"description"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	UnitPrice       pgtype.Numeric     `json:"unit_price"`
	Amount          pgtype.Numeric     `json:"amount"`
	JournalID       uuid.NullUUID      `json:"journal_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
}

type BillingPeriod struct {
	ID        uuid.UUID          `json:"id"`
	Year      int32              `json:"year"`
	Label     string             `json:"label"`
	Status    string             `json:"status"`
	Note      pgtype.Text        `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy uuid.NullUUID      `json:"created_by"`
	UpdatedBy uuid.NullUUID      `json:"updated_by"`
}

type BillingSnapshot struct {
	ID              uuid.UUID          `json:"id"`
	BillingPeriodID uuid.UUID          `json:"billing_period_id"`
	SnapshotData    []byte             `json:"snapshot_data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
}

type Deposit struct {
	ID        uuid.UUID          `json:"id"`
	LeaseID   uuid.UUID          `json:"lease_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	Currency  string             `json:"currency"`
	Status    string             `json:"status"`
	JournalID uuid.NullUUID      `json:"journal_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy uuid.NullUUID      `json:"created_by"`
	UpdatedBy uuid.NullUUID      `json:"updated_by"`
}

type Document struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	FilePath       string             `json:"file_path"`
	MimeType       pgtype.Text        `json:"mime_type"`
	FileSizeBytes  pgtype.Int8        `json:"file_size_bytes"`
	ChecksumSha256 pgtype.Text        `json:"checksum_sha256"`
	IsPublic       bool               `json:"is_public"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy      uuid.NullUUID      `json:"created_by"`
	UpdatedBy      uuid.NullUUID      `json:"updated_by"`
	SearchVector   interface{}        `json:"search_vector"`
}

type DocumentCategory struct {
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	IsProtected bool        `json:"is_protected"`
}

type DocumentRelation struct {
	DocumentID   uuid.UUID          `json:"document_id"`
	CategorySlug string             `json:"category_slug"`
	TargetType   string             `json:"target_type"`
	TargetPk     string             `json:"target_pk"`
	Note         pgtype.Text        `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    uuid.NullUUID      `json:"created_by"`
}

type DunningNotice struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	DunningLevel  int32              `json:"dunning_level"`
	Reason        string             `json:"reason"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferencePk   pgtype.Text        `json:"reference_pk"`
	AmountDue     pgtype.Numeric     `json:"amount_due"`
	DunningFee    pgtype.Numeric     `json:"dunning_fee"`
	DueDate       pgtype.Date        `json:"due_date"`
	Status        string             `json:"status"`
	ApprovedBy    uuid.NullUUID      `json:"approved_by"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
	DocumentID    uuid.NullUUID      `json:"document_id"`
	JournalID     uuid.NullUUID      `json:"journal_id"`
	Note          pgtype.Text        `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy     uuid.NullUUID      `json:"created_by"`
	UpdatedBy     uuid.NullUUID      `json:"updated_by"`
}

type ExpenseClaim struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	ReceiptDocumentID uuid.NullUUID      `json:"receipt_document_id"`
	JournalID         uuid.NullUUID      `json:"journal_id"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy         uuid.NullUUID      `json:"created_by"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
}

type Garage struct {
	UnitID    uuid.UUID          `json:"unit_id"`
	Nr        string             `json:"nr"`
	AreaSqm   pgtype.Numeric     `json:"area_sqm"`
	MeterID   pgtype.Text        `json:"meter_id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Group struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	GroupType   string             `json:"group_type"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

type GroupMember struct {
	GroupID     uuid.UUID          `json:"group_id"`
	UserID      uuid.UUID          `json:"user_id"`
	RoleInGroup string             `json:"role_in_group"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	LeftAt      pgtype.Timestamptz `json:"left_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
}

type Incident struct {
	ID                     uuid.UUID          `json:"id"`
	SubjectUserID          uuid.NullUUID      `json:"subject_user_id"`
	SubjectUnitID          uuid.NullUUID      `json:"subject_unit_id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	Category               string             `json:"category"`
	Severity               string             `json:"severity"`
	IncidentDate           pgtype.Date        `json:"incident_date"`
	IncidentTime           pgtype.Time        `json:"incident_time"`
	LocationDescription    pgtype.Text        `json:"location_description"`
	LegalProvisionID       uuid.NullUUID      `json:"legal_provision_id"`
	LegalBasisReference    pgtype.Text        `json:"legal_basis_reference"`
	LegalBasisText         pgtype.Text        `json:"legal_basis_text"`
	Status                 string             `json:"status"`
	ResolutionNote         pgtype.Text        `json:"resolution_note"`
	AiSuggestedSeverity    pgtype.Text        `json:"ai_suggested_severity"`
	AiSuggestedCategory    pgtype.Text        `json:"ai_suggested_category"`
	AiSuggestedProvisionID uuid.NullUUID      `json:"ai_suggested_provision_id"`
	AiConfidence           pgtype.Numeric     `json:"ai_confidence"`
	ReportedBy             uuid.UUID          `json:"reported_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              uuid.NullUUID      `json:"created_by"`
	UpdatedBy              uuid.NullUUID      `json:"updated_by"`
	SearchVector           interface{}        `json:"search_vector"`
}

type IncidentConsequence struct {
	IncidentID      uuid.UUID          `json:"incident_id"`
	ConsequenceType string             `json:"consequence_type"`
	ConsequencePk   uuid.UUID          `json:"consequence_pk"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
}

type IncidentWitness struct {
	ID             uuid.UUID          `json:"id"`
	IncidentID     uuid.UUID          `json:"incident_id"`
	WitnessUserID  uuid.NullUUID      `json:"witness_user_id"`
	WitnessName    pgtype.Text        `json:"witness_name"`
	WitnessContact pgtype.Text        `json:"witness_contact"`
	Statement      string             `json:"statement"`
	StatementDate  pgtype.Date        `json:"statement_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      uuid.NullUUID      `json:"created_by"`
}

type InventoryItem struct {
	ID          uuid.UUID          `json:"id"`
	UnitID      uuid.UUID          `json:"unit_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

type Lease struct {
	ID             uuid.UUID          `json:"id"`
	UnitID         uuid.UUID          `json:"unit_id"`
	TenantUserID   uuid.UUID          `json:"tenant_user_id"`
	LandlordUserID uuid.NullUUID      `json:"landlord_user_id"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	Status         string             `json:"status"`
	Note           pgtype.Text        `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy      uuid.NullUUID      `json:"created_by"`
	UpdatedBy      uuid.NullUUID      `json:"updated_by"`
}

type LegalProvision struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Title     string             `json:"title"`
	Source    string             `json:"source"`
	Reference string             `json:"reference"`
	FullText  string             `json:"full_text"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy uuid.NullUUID      `json:"created_by"`
}

type LendableItem struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	ItemMode        string             `json:"item_mode"`
	SerialNumber    pgtype.Text        `json:"serial_number"`
	QuantityTotal   int32              `json:"quantity_total"`
	StockTotal      pgtype.Int4        `json:"stock_total"`
	StockAvailable  pgtype.Int4        `json:"stock_available"`
	Condition       pgtype.Text        `json:"condition"`
	DailyFee        pgtype.Numeric     `json:"daily_fee"`
	DepositAmount   pgtype.Numeric     `json:"deposit_amount"`
	ImageDocumentID uuid.NullUUID      `json:"image_document_id"`
	Note            pgtype.Text        `json:"note"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
	UpdatedBy       uuid.NullUUID      `json:"updated_by"`
	SearchVector    interface{}        `json:"search_vector"`
}

type LendingRecord struct {
	ID                  uuid.UUID          `json:"id"`
	ItemID              uuid.UUID          `json:"item_id"`
	BorrowerUserID      uuid.NullUUID      `json:"borrower_user_id"`
	BorrowerGroupID     uuid.NullUUID      `json:"borrower_group_id"`
	Quantity            int32              `json:"quantity"`
	Status              string             `json:"status"`
	ReservedFrom        pgtype.Date        `json:"reserved_from"`
	ReservedUntil       pgtype.Date        `json:"reserved_until"`
	CheckedOutAt        pgtype.Timestamptz `json:"checked_out_at"`
	ReturnedAt          pgtype.Timestamptz `json:"returned_at"`
	ConditionOnCheckout pgtype.Text        `json:"condition_on_checkout"`
	ConditionOnReturn   pgtype.Text        `json:"condition_on_return"`
	FeeCharged          pgtype.Numeric     `json:"fee_charged"`
	JournalID           uuid.NullUUID      `json:"journal_id"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy           uuid.NullUUID      `json:"created_by"`
	UpdatedBy           uuid.NullUUID      `json:"updated_by"`
}

type MeterReading struct {
	ID          uuid.UUID          `json:"id"`
	UnitID      uuid.UUID          `json:"unit_id"`
	ReadingDate pgtype.Date        `json:"reading_date"`
	ValKwh      pgtype.Numeric     `json:"val_kwh"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

type Parcel struct {
	UnitID             uuid.UUID          `json:"unit_id"`
	Nr                 string             `json:"nr"`
	GardenAreaSqm      pgtype.Numeric     `json:"garden_area_sqm"`
	BuildingAreaSqm    pgtype.Numeric     `json:"building_area_sqm"`
	CommunityAreaSqm   pgtype.Numeric     `json:"community_area_sqm"`
	TotalAreaSqm       pgtype.Numeric     `json:"total_area_sqm"`
	BuildingValue      pgtype.Numeric     `json:"building_value"`
	HasBuildingPermit  bool               `json:"has_building_permit"`
	MeterElectricityID pgtype.Text        `json:"meter_electricity_id"`
	MeterWaterID       pgtype.Text        `json:"meter_water_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Permission struct {
	Slug        string `json:"slug"`
	Description string `json:"description"`
	IsProtected bool   `json:"is_protected"`
}

type Role struct {
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	IsProtected bool               `json:"is_protected"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

type RolePermission struct {
	RoleSlug       string `json:"role_slug"`
	PermissionSlug string `json:"permission_slug"`
}

type SharedLink struct {
	ID         uuid.UUID          `json:"id"`
	Slug       string             `json:"slug"`
	TargetType string             `json:"target_type"`
	TargetPk   pgtype.Text        `json:"target_pk"`
	CustomUrl  pgtype.Text        `json:"custom_url"`
	IsPublic   bool               `json:"is_public"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	MaxVisits  pgtype.Int4        `json:"max_visits"`
	VisitCount int32              `json:"visit_count"`
	PinCode    pgtype.Text        `json:"pin_code"`
	Context    pgtype.Text        `json:"context"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy  uuid.NullUUID      `json:"created_by"`
}

type Termination struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	LeaseID             uuid.NullUUID      `json:"lease_id"`
	TerminationType     string             `json:"termination_type"`
	Reason              string             `json:"reason"`
	LegalProvisionID    uuid.NullUUID      `json:"legal_provision_id"`
	LegalBasisText      pgtype.Text        `json:"legal_basis_text"`
	NoticeDate          pgtype.Date        `json:"notice_date"`
	EffectiveDate       pgtype.Date        `json:"effective_date"`
	ClearanceDeadline   pgtype.Date        `json:"clearance_deadline"`
	ObjectionDeadline   pgtype.Date        `json:"objection_deadline"`
	ObjectionReceivedAt pgtype.Timestamptz `json:"objection_received_at"`
	ObjectionText       pgtype.Text        `json:"objection_text"`
	BoardResolutionDate pgtype.Date        `json:"board_resolution_date"`
	Status              string             `json:"status"`
	ApprovedBy          uuid.NullUUID      `json:"approved_by"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
	DocumentID          uuid.NullUUID      `json:"document_id"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy           uuid.NullUUID      `json:"created_by"`
	UpdatedBy           uuid.NullUUID      `json:"updated_by"`
}

type Unit struct {
	ID           uuid.UUID          `json:"id"`
	UnitType     string             `json:"unit_type"`
	Label        string             `json:"label"`
	Note         pgtype.Text        `json:"note"`
	IsProtected  bool               `json:"is_protected"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy    uuid.NullUUID      `json:"created_by"`
	UpdatedBy    uuid.NullUUID      `json:"updated_by"`
	SearchVector interface{}        `json:"search_vector"`
}

type UnitOwnership struct {
	ID          uuid.UUID          `json:"id"`
	UnitID      uuid.UUID          `json:"unit_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

type UnitWorkHourObligation struct {
	ID              uuid.UUID          `json:"id"`
	UnitID          uuid.UUID          `json:"unit_id"`
	Year            int32              `json:"year"`
	AdditionalHours pgtype.Numeric     `json:"additional_hours"`
	Reason          string             `json:"reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	IsActive     bool               `json:"is_active"`
	IsProtected  bool               `json:"is_protected"`
	AnonymizedAt pgtype.Timestamptz `json:"anonymized_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy    uuid.NullUUID      `json:"created_by"`
	UpdatedBy    uuid.NullUUID      `json:"updated_by"`
	SearchVector interface{}        `json:"search_vector"`
}

type UserAddress struct {
	UserID      uuid.UUID          `json:"user_id"`
	Company     pgtype.Text        `json:"company"`
	CareOf      pgtype.Text        `json:"care_of"`
	Street1     string             `json:"street1"`
	Street2     pgtype.Text        `json:"street2"`
	PostalCode  string             `json:"postal_code"`
	City        string             `json:"city"`
	State       pgtype.Text        `json:"state"`
	CountryCode string             `json:"country_code"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.NullUUID      `json:"created_by"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

type UserContactPoint struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	ContactType         string             `json:"contact_type"`
	Label               pgtype.Text        `json:"label"`
	Value               string             `json:"value"`
	IsPrimary           bool               `json:"is_primary"`
	IsPreferred         bool               `json:"is_preferred"`
	AllowContact        bool               `json:"allow_contact"`
	PreferredTimeWindow pgtype.Text        `json:"preferred_time_window"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy           uuid.NullUUID      `json:"created_by"`
	UpdatedBy           uuid.NullUUID      `json:"updated_by"`
}

type UserPreference struct {
	UserID               uuid.UUID          `json:"user_id"`
	PreferredContactType pgtype.Text        `json:"preferred_contact_type"`
	Note                 pgtype.Text        `json:"note"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy            uuid.NullUUID      `json:"updated_by"`
}

type UserRole struct {
	UserID     uuid.UUID          `json:"user_id"`
	RoleSlug   string             `json:"role_slug"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy uuid.NullUUID      `json:"assigned_by"`
}

type UserTotpSecret struct {
	UserID            uuid.UUID          `json:"user_id"`
	SecretEncrypted   string             `json:"secret_encrypted"`
	IsEnabled         bool               `json:"is_enabled"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	RecoveryCodesHash []string           `json:"recovery_codes_hash"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	FailedAttempts    int32              `json:"failed_attempts"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserWorkHourAdjustment struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Year          int32              `json:"year"`
	AdjustedHours pgtype.Numeric     `json:"adjusted_hours"`
	Reason        string             `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy     uuid.NullUUID      `json:"created_by"`
}

type ViewRevisionReport struct {
	Zeitpunkt       pgtype.Timestamptz `json:"zeitpunkt"`
	Bearbeiter      interface{}        `json:"bearbeiter"`
	Bereich         string             `json:"bereich"`
	Aktion          string             `json:"aktion"`
	DatensatzID     string             `json:"datensatz_id"`
	GeaenderteWerte []byte             `json:"geaenderte_werte"`
	StandVorher     []byte             `json:"stand_vorher"`
	StandNachher    []byte             `json:"stand_nachher"`
}

type ViewWorkHourBalance struct {
	UserID            uuid.UUID      `json:"user_id"`
	Name              interface{}    `json:"name"`
	Year              int32          `json:"year"`
	BaseHours         pgtype.Numeric `json:"base_hours"`
	UnitHours         pgtype.Numeric `json:"unit_hours"`
	Adjustment        pgtype.Numeric `json:"adjustment"`
	TotalRequired     int32          `json:"total_required"`
	HoursWorked       int64          `json:"hours_worked"`
	HoursMissing      interface{}    `json:"hours_missing"`
	ReplacementFee    int32          `json:"replacement_fee"`
	Deadline          pgtype.Date    `json:"deadline"`
	FeePerMissingHour pgtype.Numeric `json:"fee_per_missing_hour"`
}

type Warning struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	WarningType        string             `json:"warning_type"`
	Severity           string             `json:"severity"`
	Description        string             `json:"description"`
	IssuedDate         pgtype.Date        `json:"issued_date"`
	ValidUntil         pgtype.Date        `json:"valid_until"`
	ResponseDeadline   pgtype.Date        `json:"response_deadline"`
	ResponseReceivedAt pgtype.Timestamptz `json:"response_received_at"`
	ResponseText       pgtype.Text        `json:"response_text"`
	Status             string             `json:"status"`
	ApprovedBy         uuid.NullUUID      `json:"approved_by"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	LegalProvisionID   uuid.NullUUID      `json:"legal_provision_id"`
	DocumentID         uuid.NullUUID      `json:"document_id"`
	Note               pgtype.Text        `json:"note"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy          uuid.NullUUID      `json:"created_by"`
	UpdatedBy          uuid.NullUUID      `json:"updated_by"`
}

type WebhookSubscription struct {
	ID              uuid.UUID          `json:"id"`
	HookName        string             `json:"hook_name"`
	TargetUrl       string             `json:"target_url"`
	Secret          pgtype.Text        `json:"secret"`
	IsActive        bool               `json:"is_active"`
	RetryCount      int32              `json:"retry_count"`
	TimeoutMs       int32              `json:"timeout_ms"`
	LastTriggeredAt pgtype.Timestamptz `json:"last_triggered_at"`
	LastStatusCode  pgtype.Int4        `json:"last_status_code"`
	FailureCount    int32              `json:"failure_count"`
	Note            pgtype.Text        `json:"note"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy       uuid.NullUUID      `json:"created_by"`
}

type WorkEvent struct {
	ID                      uuid.UUID          `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	EventDate               pgtype.Date        `json:"event_date"`
	StartTime               pgtype.Time        `json:"start_time"`
	EndTime                 pgtype.Time        `json:"end_time"`
	Location                pgtype.Text        `json:"location"`
	MinParticipants         pgtype.Int4        `json:"min_participants"`
	MaxParticipants         pgtype.Int4        `json:"max_participants"`
	HoursCredited           pgtype.Numeric     `json:"hours_credited"`
	Status                  string             `json:"status"`
	CancellationReason      pgtype.Text        `json:"cancellation_reason"`
	AiSuggestedDate         pgtype.Date        `json:"ai_suggested_date"`
	AiSuggestionReason      pgtype.Text        `json:"ai_suggestion_reason"`
	AiParticipantSuggestion []byte             `json:"ai_participant_suggestion"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy               uuid.NullUUID      `json:"created_by"`
	UpdatedBy               uuid.NullUUID      `json:"updated_by"`
}

type WorkEventParticipant struct {
	ID             uuid.UUID          `json:"id"`
	WorkEventID    uuid.UUID          `json:"work_event_id"`
	UserID         uuid.UUID          `json:"user_id"`
	AssignedTaskID uuid.NullUUID      `json:"assigned_task_id"`
	Status         string             `json:"status"`
	InvitedAt      pgtype.Timestamptz `json:"invited_at"`
	RespondedAt    pgtype.Timestamptz `json:"responded_at"`
	AttendedFrom   pgtype.Time        `json:"attended_from"`
	AttendedUntil  pgtype.Time        `json:"attended_until"`
	HoursCredited  pgtype.Numeric     `json:"hours_credited"`
	WorkLogID      uuid.NullUUID      `json:"work_log_id"`
	Note           pgtype.Text        `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WorkEventTask struct {
	ID                   uuid.UUID          `json:"id"`
	WorkEventID          uuid.UUID          `json:"work_event_id"`
	CatalogTaskID        uuid.NullUUID      `json:"catalog_task_id"`
	Title                string             `json:"title"`
	RequiredParticipants int32              `json:"required_participants"`
	EstimatedHours       pgtype.Numeric     `json:"estimated_hours"`
	Note                 pgtype.Text        `json:"note"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type WorkHourRequirement struct {
	ID                uuid.UUID          `json:"id"`
	Year              int32              `json:"year"`
	BaseHours         pgtype.Numeric     `json:"base_hours"`
	FeePerMissingHour pgtype.Numeric     `json:"fee_per_missing_hour"`
	Deadline          pgtype.Date        `json:"deadline"`
	Note              pgtype.Text        `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         uuid.NullUUID      `json:"created_by"`
	UpdatedBy         uuid.NullUUID      `json:"updated_by"`
}

type WorkLog struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	DatePerformed pgtype.Date        `json:"date_performed"`
	HoursSpent    pgtype.Numeric     `json:"hours_spent"`
	AppliedToYear int32              `json:"applied_to_year"`
	IsVerified    bool               `json:"is_verified"`
	VerifiedBy    uuid.NullUUID      `json:"verified_by"`
	VerifiedAt    pgtype.Timestamptz `json:"verified_at"`
	Note          pgtype.Text        `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy     uuid.NullUUID      `json:"created_by"`
	UpdatedBy     uuid.NullUUID      `json:"updated_by"`
}

type WorkTaskCatalog struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Description            pgtype.Text        `json:"description"`
	Category               string             `json:"category"`
	TypicalParticipants    int32              `json:"typical_participants"`
	TypicalHours           pgtype.Numeric     `json:"typical_hours"`
	IsSeasonal             bool               `json:"is_seasonal"`
	SeasonMonths           []int32            `json:"season_months"`
	RecurrenceIntervalDays pgtype.Int4        `json:"recurrence_interval_days"`
	LastPerformedAt        pgtype.Date        `json:"last_performed_at"`
	UnitID                 uuid.NullUUID      `json:"unit_id"`
	RequiresEquipment      []string           `json:"requires_equipment"`
	Note                   pgtype.Text        `json:"note"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              uuid.NullUUID      `json:"created_by"`
	SearchVector           interface{}        `json:"search_vector"`
}
