// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_slug, permission_slug)
VALUES ($1, $2)
ON CONFLICT (role_slug, permission_slug) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleSlug       string `json:"role_slug"`
	PermissionSlug string `json:"permission_slug"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleSlug, arg.PermissionSlug)
	return err
}

const getPermissionsForRole = `-- name: GetPermissionsForRole :many
SELECT p.slug, p.description, p.is_protected
FROM role_permissions rp
JOIN permissions p ON p.slug = rp.permission_slug
WHERE rp.role_slug = $1
ORDER BY p.slug
`

func (q *Queries) GetPermissionsForRole(ctx context.Context, roleSlug string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsForRole, roleSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.Slug, &i.Description, &i.IsProtected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsForUser = `-- name: GetPermissionsForUser :many
SELECT DISTINCT p.slug
FROM user_roles ur
JOIN roles r ON r.slug = ur.role_slug AND r.deleted_at IS NULL
JOIN role_permissions rp ON rp.role_slug = ur.role_slug
JOIN permissions p ON p.slug = rp.permission_slug
WHERE ur.user_id = $1
ORDER BY p.slug
`

func (q *Queries) GetPermissionsForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT slug, description, is_protected
FROM permissions
ORDER BY slug
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.Slug, &i.Description, &i.IsProtected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM role_permissions
WHERE role_slug = $1 AND permission_slug = $2
`

type RemoveRolePermissionParams struct {
	RoleSlug       string `json:"role_slug"`
	PermissionSlug string `json:"permission_slug"`
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.Exec(ctx, removeRolePermission, arg.RoleSlug, arg.PermissionSlug)
	return err
}
