// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveUsers(ctx context.Context) (int64, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
}

var _ Querier = (*Queries)(nil)
