// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, role_slug, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_slug) DO NOTHING
`

type AssignRoleParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	RoleSlug   string        `json:"role_slug"`
	AssignedBy uuid.NullUUID `json:"assigned_by"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleSlug, arg.AssignedBy)
	return err
}

const getRole = `-- name: GetRole :one
SELECT slug, display_name, description, is_protected, created_at, updated_at
FROM roles
WHERE slug = $1 AND deleted_at IS NULL
`

type GetRoleRow struct {
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	IsProtected bool               `json:"is_protected"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRole(ctx context.Context, slug string) (GetRoleRow, error) {
	row := q.db.QueryRow(ctx, getRole, slug)
	var i GetRoleRow
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.IsProtected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT slug, display_name, description, is_protected, created_at, updated_at
FROM roles
WHERE deleted_at IS NULL
ORDER BY slug
`

type ListRolesRow struct {
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	IsProtected bool               `json:"is_protected"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.IsProtected,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.slug, r.display_name, r.description, r.is_protected
FROM user_roles ur
JOIN roles r ON r.slug = ur.role_slug
WHERE ur.user_id = $1 AND r.deleted_at IS NULL
ORDER BY r.slug
`

type ListUserRolesRow struct {
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	IsProtected bool        `json:"is_protected"`
}

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]ListUserRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRolesRow{}
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.IsProtected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRole = `-- name: RemoveRole :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_slug = $2
`

type RemoveRoleParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RoleSlug string    `json:"role_slug"`
}

func (q *Queries) RemoveRole(ctx context.Context, arg RemoveRoleParams) error {
	_, err := q.db.Exec(ctx, removeRole, arg.UserID, arg.RoleSlug)
	return err
}

const userHasRole = `-- name: UserHasRole :one
SELECT EXISTS (
  SELECT 1 FROM user_roles WHERE user_id = $1 AND role_slug = $2
)
`

type UserHasRoleParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RoleSlug string    `json:"role_slug"`
}

func (q *Queries) UserHasRole(ctx context.Context, arg UserHasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasRole, arg.UserID, arg.RoleSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
