// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: totp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTOTPSecret = `-- name: DeleteTOTPSecret :exec
DELETE FROM user_totp_secrets WHERE user_id = $1
`

func (q *Queries) DeleteTOTPSecret(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTOTPSecret, userID)
	return err
}

const getTOTPSecret = `-- name: GetTOTPSecret :one
SELECT user_id, secret_encrypted, is_enabled, verified_at, recovery_codes_hash,
       last_used_at, failed_attempts, locked_until, created_at, updated_at
FROM user_totp_secrets
WHERE user_id = $1
`

func (q *Queries) GetTOTPSecret(ctx context.Context, userID uuid.UUID) (UserTotpSecret, error) {
	row := q.db.QueryRow(ctx, getTOTPSecret, userID)
	var i UserTotpSecret
	err := row.Scan(
		&i.UserID,
		&i.SecretEncrypted,
		&i.IsEnabled,
		&i.VerifiedAt,
		&i.RecoveryCodesHash,
		&i.LastUsedAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTOTPSecret = `-- name: UpsertTOTPSecret :one
INSERT INTO user_totp_secrets (
  user_id, secret_encrypted, is_enabled, verified_at, recovery_codes_hash,
  last_used_at, failed_attempts, locked_until
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
ON CONFLICT (user_id) DO UPDATE SET
  secret_encrypted = EXCLUDED.secret_encrypted,
  is_enabled = EXCLUDED.is_enabled,
  verified_at = EXCLUDED.verified_at,
  recovery_codes_hash = EXCLUDED.recovery_codes_hash,
  last_used_at = EXCLUDED.last_used_at,
  failed_attempts = EXCLUDED.failed_attempts,
  locked_until = EXCLUDED.locked_until
RETURNING user_id, secret_encrypted, is_enabled, verified_at, recovery_codes_hash,
          last_used_at, failed_attempts, locked_until, created_at, updated_at
`

type UpsertTOTPSecretParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	SecretEncrypted   string             `json:"secret_encrypted"`
	IsEnabled         bool               `json:"is_enabled"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	RecoveryCodesHash []string           `json:"recovery_codes_hash"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	FailedAttempts    int32              `json:"failed_attempts"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) UpsertTOTPSecret(ctx context.Context, arg UpsertTOTPSecretParams) (UserTotpSecret, error) {
	row := q.db.QueryRow(ctx, upsertTOTPSecret,
		arg.UserID,
		arg.SecretEncrypted,
		arg.IsEnabled,
		arg.VerifiedAt,
		arg.RecoveryCodesHash,
		arg.LastUsedAt,
		arg.FailedAttempts,
		arg.LockedUntil,
	)
	var i UserTotpSecret
	err := row.Scan(
		&i.UserID,
		&i.SecretEncrypted,
		&i.IsEnabled,
		&i.VerifiedAt,
		&i.RecoveryCodesHash,
		&i.LastUsedAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
